### ISSUE TITLE
Removing arg type parameter from Program type?

### ISSUE THREAD

**Issue by dsyme** [elmish/elmish#138]
Can someone point me to an example where [the ``'arg`` type parameter](https://github.com/fable-elmish/elmish/blob/master/src/program.fs#L11) is important for a program?

It seems to me that the argument should _always_ be captured by the ``init`` function closure, and thus the argument type parameter is superfluous.  

If we could remove it, it would make the Program type simpler, which would be a good thing for error messages, beginners etc..

**Comment by et1975** [comment]
I'm away from a computer, but Navigation/routing in [Browser](/fable-elmish/browser) create a wrapper and feed result of the route parsing into `init`.

**Comment by dsyme** [comment]
@et1975 We cab change theprogram passed to `toNavigable` be

    (program : 'a -> Program<'model,'msg,'view>)

Hence:
```fsharp

    let toNavigable (parser : Parser<'a>)
                   (urlUpdate : 'a->'model->('model * Cmd<'msg>))
                   (program : 'a -> Program<unit,'model,'msg,'view>) =
         let program = program (parser "")
         let map (model, cmd) =
             model, cmd |> Cmd.map UserMsg

         let update msg model = 
             match msg with
             | Change location ->
                 urlUpdate (parser location) model
             | UserMsg userMsg ->
                 program.update userMsg model
             |> map

         let locationChanges (dispatch:Dispatch<_ Navigable>) : unit = (* ... *) ()

         let subs model =
             Cmd.batch
               [ [locationChanges]
                 program.subscribe model |> Cmd.map UserMsg ]

         let init () =
             program.init () |> map

         { init = init
           update = update
           subscribe = subs
           onError = program.onError
           setState = fun model dispatch -> program.setState model (UserMsg >> dispatch)
           view = fun model dispatch -> program.view model (UserMsg >> dispatch) }
```

The only difference is that ``parser ""`` is called during composition rather than at the first call to ``program.init``.  But that's ok.

**Comment by et1975** [comment]
I think that breaks the program construction flow, currently:
```fsharp
Program.mkProgram init update view
|> Program.toNavigable (parseHash pageParser) urlUpdate
|> Program.withDebugger
|> Program.withReact "elmish-app"
|> Program.run 
```

As a side note, there's the fact that some of our nesting has to happen in specific order for things to work: for example `withReact` has to follow `withDebugger` which has to follow `toNavigable`, but *all of them* are optional! Is there something in your toolbox perhaps that would eliminate `args` type and make the whole composition safer while keeping it concise?

**Comment by dsyme** [comment]
Then pass in a default initial value for 'a?

```
Program.mkProgram init update view
|> Program.toNavigable (parseHash pageParser) urlUpdate (parseHash (pageParser ""))
|> Program.withDebugger
|> Program.withReact "elmish-app"
|> Program.run 
```

That's actually clearer anyway I think.

**Comment by et1975** [comment]
I like the idea of getting rid of `args` type in principle, but the initial route is not something we want to hard code and forcing the user to call with the correct URL (segment!) using the browser API seems... counter-productive. I'll fiddle with it and see if I can comeup with something.

I'd still be curious to know if you have any thoughts about safer approach to the composition.

**Comment by dsyme** [comment]
Right, but you're hard-coding `""` in the middle of toNavigable at the moment?

**Comment by et1975** [comment]
No, you are ;)

**Comment by dsyme** [comment]
Oh yes, you're correct.  I inserted that when lifting the code out!

**Comment by et1975** [comment]
In general it would be hard to make a pure (aka testable in isolation) `init` if it doesn't take any arguments. Web apps need the args for the initial route, native apps may need it to process `intent` - arguments from the OS. This may have to wait until a better `Program` API, maybe something that avoids data structure entirely and composes functions with a CE.

**Comment by bender2k14** [comment]
What does CE stand for?

**Comment by xdaDaveShaw** [comment]
@bender2k14 - CE stands for [Computation Expression](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions).

**Comment by bender2k14** [comment]
> In general it would be hard to make a pure (aka testable in isolation) init if it doesn't take any arguments. Web apps need the args for the initial route, native apps may need it to process intent - arguments from the OS.

I don't think @dsyme is suggesting that `init` should take no arguments.  I think he is suggesting that the arguments that `init` does take don't need to be passed through Elmish.  Instead, Elmish users can partially apply their arguments to `init` and pass Elmish an `init` function with signature `unit -> 'model` (or `unit -> 'model * Cmd<'msg>`).

This style of passing arguments through Elmish also happens with `Cmd.OfFunc.either`:

https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/cmd.fs#L47-L54

Elmish requires an argument `arg` of type `'a` be passed in, but nothing is done with this argument other than passing it to the argument `task`.  It would suffice for the type of `task` to be `unit -> _` and to remove the argument `arg`.

One potential advantage of passing arguments through Elmish is to log them.  However, that is not happening in either case.

I think the other potential advantage is that the calling syntax might be cleaner in some cases.  It is definitely not cleaner in all cases though.  If the function passed in as the `init`/`task` function already has type `unit -> 'model/_`, then the calling syntax is more verbose than it would otherwise be since `()` has to be passed in as well.

> This may have to wait until a better Program API, maybe something that avoids data structure entirely and composes functions with a CE.

I am interested in making this happen.  I skimmed the CE documentation (thanks for the link @xdaDaveShaw), but it is not clicking for me how it could replace the `Program` data structure.

Is there an example someone could point me to that does the kind of thing @et1975 is thinking of?

**Comment by et1975** [comment]
Implementing program composition is not an up-for-grabs kind of issue,
especially for someone new to CEs.

**Comment by bender2k14** [comment]
No worries.  I don't mind leaving it to the Elmish experts :)

Nonetheless, I am still interested to learn this even if I don't use it in a PR for Elmish.

Is there good example of this that you could link me to?

**Comment by bender2k14** [comment]
Here is a summary of this issue as I currently understand it.

@dsyme created this issue asking if the [`'arg` type parameter on `Program`](https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L12-L13), which would make things simpler.  @et1975 likes "the idea of getting rid of `args` type in principle", but pointed out that this type parameter is being used by [`Program.toNavigable`](https://github.com/elmish/browser/blob/952ba25dc1b15a440293cde7f4756ef99b5c248a/src/navigation.fs#L114-L118) from the [browser](https://github.com/elmish/browser) repository in the [emlish ecosystem](https://github.com/elmish).  Specific issues to avoid there are hard coding the initial route (such as to `""`) and reordering the computation in ways that do not preserve behavior.

I might look into this.  The idea I have at the moment is for `browser` to define its own `Program` type in order to pass data into `init`.

**Comment by TysonMN** [comment]
I have finally spent the time to go into more detail.

A top-level application that utilizes the ability of `'arg` to be any type (instead of just `Unit`) is 
[sample-react-navigation](https://github.com/elmish/sample-react-navigation).  Here is the [composition of `Program<,,,>`](https://github.com/elmish/sample-react-navigation/blob/c5fe721b29ffcf4e75ae55d7f718495fe0d705d5/src/app.fs#L175-L179).  Although the initial `Program<,,,>` instance has `'arg` as a type other than `Unit`, it has become `Unit` by the end, which is why the [last call is to `Program.run`](https://github.com/elmish/sample-react-navigation/blob/c5fe721b29ffcf4e75ae55d7f718495fe0d705d5/src/app.fs#L179) instead of `Program.runWith`.  As a side note, it is interesting that the example given to justify the use of `'arg` being a type other than `Unit` is not also an example to justify the existence of [`Program.runWith`](https://github.com/elmish/elmish/blob/d3705fb474e65b0dd084bfd9f0772175f1f3899c/src/program.fs#L134)

`'arg` is changed from its initial non-`Unit` type to `Unit` in
- the call to [`Program.toNavigable`](https://github.com/elmish/sample-react-navigation/blob/c5fe721b29ffcf4e75ae55d7f718495fe0d705d5/src/app.fs#L176) defined [here](https://github.com/elmish/browser/blob/952ba25dc1b15a440293cde7f4756ef99b5c248a/src/navigation.fs#L114-L118),
- which calls [`Internal.toNavigableWith`](Internal.toNavigableWith) defined [here](https://github.com/elmish/browser/blob/952ba25dc1b15a440293cde7f4756ef99b5c248a/src/navigation.fs#L79),
- which [maps](https://github.com/elmish/browser/blob/952ba25dc1b15a440293cde7f4756ef99b5c248a/src/navigation.fs#L100-L101) the original `init` function that accepts a non-`Unit` input to a new `init` function that accepts `Unit` as its input,
- which references the static global value `window` (of type [`Window`](https://github.com/fable-compiler/fable-browser/blob/3c31c050e6315ce3703d98c1d234b15c851ab262/src/Dom/Browser.Dom.fs#L808)) declared [here](https://github.com/fable-compiler/fable-browser/blob/3c31c050e6315ce3703d98c1d234b15c851ab262/src/Dom/Browser.Dom.Api.fs#L26),
- but more specifically references the mutable `location` property (of type [`Location`](https://github.com/fable-compiler/fable-browser/blob/3c31c050e6315ce3703d98c1d234b15c851ab262/src/Dom/Browser.Dom.fs#L770)) on `Window` defined [here](https://github.com/fable-compiler/fable-browser/blob/3c31c050e6315ce3703d98c1d234b15c851ab262/src/Dom/Browser.Dom.fs#L837).

That is where I stopped my static analysis.  I don't think there is much hope in me statically analyzing mutable data.

That is far enough though to understand how the `init` function provided by the user is called.  WIthout preserving all the behavior of the original `Program.toNavigable` call, the following code compiles and calls the `init` function provided by the user in the same way.

```F#
let initAcceptingUnit () =
  (pageParser, window.location)
  ||> parseHash 
  |> init

// App
Program.mkProgram initAcceptingUnit update view
//|> Program.toNavigable (parseHash pageParser) urlUpdate
|> Program.withReactSynchronous "elmish-app"
|> Program.withDebugger
|> Program.run
```

---

Therefore, after @et1975 said this in https://github.com/elmish/elmish/issues/138#issuecomment-364127348...

> I like the idea of getting rid of `args` type in principle, but the initial route is not something we want to hard code and forcing the user to call with the correct URL (segment!) using the browser API seems... counter-productive. I'll fiddle with it and see if I can comeup with something.
>
> I'd still be curious to know if you have any thoughts about safer approach to the composition.

...instead of this response by @dsyme...

> Right, but you're hard-coding ""  in the middle of toNavigable at the moment?

...I think it was be accurate to say

> Right, but you're hard-coding `window.location` in the implementation of `toNavigable` at the moment?

---

Quoting @et1975 from https://github.com/elmish/elmish/issues/138#issuecomment-364110956
> As a side note, there's the fact that some of our nesting has to happen in specific order for things to work: for example `withReact` has to follow `withDebugger` which has to follow `toNavigable`, but all of them are optional! Is there something in your toolbox perhaps that would eliminate `args` type and make the whole composition safer while keeping it concise?

Conciseness might be up for debate, but the safety would be improved if `toNavigable` were pure.  At least one reason it is impure is its dependence on `window.location`.
