### ISSUE TITLE
Fable 2

### ISSUE THREAD

**Issue by alfonsogarciacaro** [elmish/elmish#152]
Could you please update dependencies to Fable.Core/Fable.PowerPack 2 (prerelease) and release a prerelease version?

**Comment by MangelMaxime** [comment]
We will need to use Thoth.Json in this one too.

I tested it today, and this kind of code is working:

```fs
let withConsoleTrace (program: Program<'arg, 'model, 'msg, 'view>) =
    let traceInit (arg:'arg) =
        let initModel,cmd = program.init arg
        JS.console.log("Initial state:", initModel)
        initModel,cmd

    let traceUpdate (msg : 'msg) (model : 'model) =
        JS.console.log("New message:",  Encode.Auto.toString 4 msg)
        let newModel,cmd = program.update msg model
        JS.console.log("Updated state:", Encode.Auto.toString 4 newModel)
        newModel,cmd

    { program with
        init = traceInit
        update = traceUpdate }
```

I will send a PR

**Comment by MangelMaxime** [comment]
One question, should we release it under `2.0.0-beta-3` or something else ?

I am asking because until now `2.0.0-beta-X` was used for the *Invert dispatch and model parameters in view* proposition.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime I think it's working even if you pass the object as is: `JS.console.log("New message:", msg)` and the browser dev tools (at least in Chrome) will let you fold/unfold the object.

**Comment by et1975** [comment]
We definitely should preserve the fold/unfold capability of object logging. I think the roundtripping to JSON was done because we had all those F#/Fable members that we didn't want to expose, which shouldn't be required anymore, right? Same goes for debugger, I think.

Re: version... yeah, I think I'd like to rename current 2.0 branch to something else and deprecate the existing nuget betas, continue with the numbering, so it would be `2.0.0-beta-4`. I'll prepare the branches and let you guys know.

**Comment by alfonsogarciacaro** [comment]
I need to check, but I think the console ignores the methods attached to the prototype and only takes the fields attached directly to the object itself. As Fable 2 now includes the case name in union instances, it should be ok to log them as-is.

**Comment by MangelMaxime** [comment]
I need to test Alfonso methods but `Encode.Auto.toString 4 msg)` do allow you to fold/unfold.

I am fighting again with the doc generation which is broken, since FAKE5 update of the repo I guess...

**Comment by MangelMaxime** [comment]
Ok both `console.log("Updated state:", Encode.Auto.toString 4 newModel)` and `console.log("Updated state:", newModel)` seems to have a similar result.

**Comment by alfonsogarciacaro** [comment]
Sorry, I just realized there was an error with the Fable.Powerpack 2.0.0-beta-001 package. Apparently I forgot how to publish Fable libraries. It's fixed in  2.0.0-beta-003.

**Comment by et1975** [comment]
Reset the master on the v1.x branch (sorry if it messes up someone's state!) and released it with Fable2 as dependency. The previous master ref now exists as reverse-args branch.

**Comment by MangelMaxime** [comment]
@et1975 I released all stable version of `Fable.Elmish.*` packages. I am doing that because I am preparing the migration guide from Fable 1 to Fable 2 and it's better if people can remove all `prerelease` tags.

However, I am not a maintainer of [Elmish](https://www.nuget.org/packages/Elmish) package so I wasn't able to publish it.

**Comment by et1975** [comment]
Thanks, pushed.
