### ISSUE TITLE
Possibility of keeping the update loop running in WPF when using ShowDialog

### ISSUE THREAD

**Issue by cmeeren** [elmish/elmish#177]
Currently in Elmish.WPF, if a modal window is opened using `ShowDialog`, the Elmish update loop is blocked. All messages are queued, and when the window is closed, all the queued messages are sent through.

Do you know why, and is could there be a way to keep the Elmish update loop running when displaying a modal window?

**Comment by et1975** [comment]
It's been a while since I dug into Windows threading, but here's what I think is happening:
1) elmish 3.x runs the dispatch on the thread it's called on, in WPF case that's the UI thread
2) UI thread uses Win32's own dispatch loop, which is tied to each window individually
3) Modal window blocks Win32 dispatching on main window

I've seen this happen before in one form or another, but I'm coming up short on details or the ideas for working around that. 
Maybe @ReedCopsey has some ideas?

**Comment by cmeeren** [comment]
This is no longer a problem. We just open the dialog asynchronously. It blocks the UI, but not the Elmish loop.
