### ISSUE TITLE
Is update doing too much when returning 'model * Cmd<'msg>?

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#188]
As I write my first Elmish program, I am annoyed at how much more difficult it is to compose the more complicated `update` function--the variant that ultimately returns a pair of type `'model * Cmd<'msg>`.  When `update` doesn't return a pair (and instead just returns something of type `'model`), the composition of `update` is a simple one-liner and looks like
```fs
module Parent =
  type Model = { Child: Child.Model }
  type Msg = ChildMsg of Child.Msg
  let update msg m =
    match msg with
    | ChildMsg msg' -> { m with Child = Child.update msg' m.Child }
```

But when `update` returns a pair of type `'model * Cmd<'msg>`, then I can't see a better way of composing it than this two liner
```fs
module Parent =
  type Model = { Child: Child.Model }
  type Msg = ChildMsg of Child.Msg
  let update msg m =
    match msg with
    | ChildMsg msg' ->
      let (m', cmds) = Child.update msg' m.Child
      { m with Child = m' }, cmds |> Cmd.map ChildMsg
```

Of course nothing is free in life, so something has to "get worse" in order to express programs that want Elmish to execute impure code for them.

But why make `update` worse by having it return two things?

Why not instead have two functions that each return one thing?  More specifically, why not "make things worse" by introducing another function to return the additional information?
```fs
// 'msg -> 'model -> 'model
let update msg m =
  match msg with
  | ChildMsg msg' -> { m with Child = Child.update msg' m.Child }

// 'msg -> 'model -> 'model -> Cmd<'msg>`
let effect msg oldModel newModel ->
  match msg with
  | ChildMsg msg' -> Child.effect msg' oldModel.Child newModel.Child |> Cmd.map ChildMsg
```

Naming is hard, so there is likely a better name for this function than `effect`.  (I will speak with my company's "naming expert" and probably suggest a better name some time next week.)

I had this `effect` function take in both the old and new models since in some cases, the refactor to use this `effect` would be easier than just taking in one model.  And if only one model was given, then I think the refactor would be easier if given the old model since getting the new model could be done by calling `update`.  In practice though, I would expect that it suffices for `effect` to only take in the new model since the developer could ensure that anything needed by `effect` is available on the new model.

The idea for splitting the "completed" `update` into the "simple" `update` and this `effect` function occurred to me when considering what [Elmish.Streams](https://github.com/dbrattli/Elmish.Streams) is doing.  Specifically, @johannesegger [commented](https://github.com/dbrattli/Elmish.Streams/issues/25#issuecomment-506827025) that by using Elmish.Streams, he is
> really happy that Cmds are now gone (e.g. composition of updates got much better, because it's just a simple fold when you only have the model).

Elimsh.Streams seems like it solves a much more interesting problem (...I am intrigued and still looking into it), but the fact that it also makes `update` more composable seems like an accident to me since `update` never needed to return a pair of things in the first place.

**Comment by MangelMaxime** [comment]
Hello, 

> But why make update worse by having it return two things?

It's not worse, it's just flexible to your needs because it's just a function.

> Why not instead have two functions that each return one thing? More specifically, why not "make things worse" by introducing another function to return the additional information?

Because then you have to code the logic of your application twice, also which model state will you have in `effect`?

Remember that everything is a function in Elmish and so `update` signature is not fixed you can pass 2 arguments or 5 of them. Same as you can return a tuple of 2 or more, a record, etc. depending on what you are doing.

I mentioned this point in my blog post: https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd

What will you do if you need to sometimes return a tuple of 3 from `update` function and sometimes 2?

If you don't want to write the composition function yourself all the time, it's always possible to create layers/helpers in order to do the composition.

```fs
let update msg model =
    match msg with
    | ChildMsg childMsg ->
        Update.compose Child.update childMsg model.ChildModel
```

----------

`Elmish.Streams` is also having its own problem and hacks while most of the time you can use standard React features as an equivalent of that library. The "only" missing things in term of Elmish architecture compared to `Elmish.Stream` is an elm like subscription which gets called each time the model update. And this has been decided to explore this idea.

I am aware that `Elmish.Streams` provides support for `Obersables` and some other things.

You can read the discussion in this thread: https://github.com/elmish/elmish/issues/183

**Comment by bender2k14** [comment]
Huh.  Overall, I feel like I didn't express myself clearly enough.

> > But why make `update` worse by having it return two things?
> 
> It's not worse, it's just flexible to your needs because it's just a function.

I think "worse" was a bad choice of words on my part.  I meant to express some idea that was beyond debate--that everyone would agree with.

What if I described that `update` function as more complicated by saying
> But why make `update` ~worse~ _more complicated_ by having it return two things?

If I need to clarify this even further, then I mean "complicated" in the sense that Rich Hickey unpacks in his talk called [Simple made easy](https://www.youtube.com/watch?v=34_L7t7fD_U).

> Because then you have to code the logic of your application twice

I am not sure I understand what you mean.  Can you elaborate?  I agree that the syntax for the pattern match on the message type would have to appear twice (once in `update` and once in `effect`).  I wouldn't think to call this pattern match syntax logic though.  Is there something else beyond that syntax that must be duplicated?  Something that could not be easily deduplicated with helper functions?

> ...which model state will you have in effect?

I must not have clearly expressed myself about that either.  For simplicity, I am suggesting that both the old model and the new model be passed into `effect`.  That way, we don't get distracted about which model instance is the "correct" one.  Then as an aside, I wrote a whole paragraph specifically about just passing in one model instance.  Do you have a more specific question along these lines that I failed to address in that paragraph?

> Remember that everything is a function in Elmish and so update signature is not fixed you can pass 2 arguments or 5 of them. Same as you can return a tuple of 2 or more, a record, etc. depending on what you are doing.
> 
> I mentioned this point in my blog post: https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd

This reminds me of the Corinthians that Paul quoted in 1 Corinthians 10:23 when he said
> "I have the right to do anything," you say--but not everything is beneficial. "I have the right to do anything"--but not everything is constructive.

Yes, I agree with you that many things are syntactically possible in F#.  I am trying to have a conversation about which syntactic choices would be more beneficial or more constructive.  Which syntactic choices would help us to write better code?  Instead of considering anything that anyone could possibly write in F#, I am trying to focus our attention on two specific possibilities.

I am asking about the tradeoffs between
```
update : 'msg -> 'model -> 'model * Cmd<'msg>
```

and
```
update : 'msg -> 'model -> 'model
effect : 'msg -> 'model -> 'model -> Cmd<'msg>
```

> What will you do if you need to sometimes return a tuple of 3 from update function and sometimes 2?

"Need" is a strong word.  Few things are necessary.  To humor you though, I don't know what I would do.  That is why I created this issue.  To discuss potential edge cases like this that I am unable to think of myself.

Is there a specific situation that you have in mind that you are willing to share with us so that we could discuss it in more detail?

As a default approach though, I would likely create a third function to return the third item of the pair.

> If you don't want to write the composition function yourself all the time, it's always possible to create layers/helpers in order to do the composition.

In your code that follows this part I quoted, I don't know how `Update.compose` is implemented.  Could you share the implementation with us?

> You can read the discussion in this thread: #183

Indeed.  I have the penultimate comment in that issue.

**Comment by Zaid-Ajaj** [comment]
You know you could just break the update function into two smaller functions, right?
```fs
let update (msg: Msg) (state: State) : State = state
let effect (msg: Msg) (state: State) : Cmd<Msg> = Cmd.none

let update' (msg: Msg) (state: State) : State * Cmd<Msg> = 
  let nextState =  update msg state
  let nextCmd = effect msg state
  nextState, nextCmd
```

**Comment by MangelMaxime** [comment]
> > Because then you have to code the logic of your application twice
> 
> I am not sure I understand what you mean. Can you elaborate? I agree that the syntax for the pattern match on the message type would have to appear twice (once in `update` and once in `effect`). I wouldn't think to call this pattern match syntax logic though. Is there something else beyond that syntax that must be duplicated? Something that could not be easily deduplicated with helper functions?

A match is not always straightforward, for example code taken from one of my application:

*I didn't make it slim on purpose to share the complexity*

```fs
    | Loaded (originalData, activeTab), SwitchToMap ->
        match activeTab with
        | Tab.Map tabData ->
            Loaded(originalData, Tab.Map tabData), Cmd.none

        | _ ->
            let (mapModel, mapCmd) = Map.init { Session = currentUser
                                                DomainId = originalData.Id }
            Loaded(originalData, Tab.Map mapModel), Cmd.map MapMsg mapCmd
```

```fs
    | Page.ResetAccount resetAccountModel, ResetAccountMsg resetAccountMsg ->
        let (newResetAccountModel, newResetAccountMsg) = ResetAccount.update resetAccountMsg resetAccountModel
        { model with ActivePage = Page.ResetAccount newResetAccountModel }, Cmd.map ResetAccountMsg newResetAccountMsg

    | Page.AuthPage authPage, _ ->
        match model.Session with
        | Some user ->
            match authPage, msg with
            | AuthPage.Administration subModel, AdministrationMsg subMsg ->
                let (newSubModel, subCmd) = Administration.update user subMsg subModel
                { model with ActivePage = Page.AuthPage << AuthPage.Administration <| newSubModel }, Cmd.map AdministrationMsg subCmd

            | AuthPage.DomainMap subModel, DomainMapMsg subMsg ->
                let (newSubModel, subCmd) = Domain.Map.Component.update user subMsg subModel
                { model with ActivePage = Page.AuthPage << AuthPage.DomainMap <| newSubModel }, Cmd.map DomainMapMsg subCmd

            | _, y ->
                JS.console.warn("AuthPage, message discarded:\n", string y)
                model, Cmd.none

        | None -> model, Router.newUrl (Router.Route.Errored Router.LoginRequired)

    | _, y ->
        let error = string y
        if error.Contains("BadStatus") then
            Browser.WebStorage.localStorage.removeItem("session")
            Router.modifyLocation Router.Route.Login
            { model with Session = None }, Cmd.none
        else
            JS.console.warn("Message discarded:\n", string y)
            model, Cmd.none
```

If I have to use `effect` then I would have this code duplicated and I don't want that. It's already hard enough to make sure everything is right in a single place :)

Yes, it's possible to create helpers, but I think it will make the code harder to read because we have to name them. Don't have the logic directly under the eyes, etc. Today, I can read my update function and understand everything at glance without having to navigate between different functions.

> I must not have clearly expressed myself about that either. For simplicity, I am suggesting that both the old model and the new model be passed into effect.

Sorry, I missed this paragraph :)

How would we initialize the components?

```fs
let (editingModel, creatingCmd) = Modal.initEmpty data
{ model with State = State.Editing editingModel }, Cmd.map EditingMsg creatingCmd
```

Would we have `init` and `initEffect` functions? Which will again lead to possible code duplication? What if I am restructuring the data to use a `Guid` as an identifier for the messages

```fs
| ChildMsg of Guid * DumpMarker.Msg
```

Then, I need to store in each child if they are initialized in order to get access to the right `Guid` value.

> "Need" is a strong word. Few things are necessary. To humor you though, I don't know what I would do. That is why I created this issue. To discuss potential edge cases like this that I am unable to think of myself.
> 
> Is there a specific situation that you have in mind that you are willing to share with us so that we could discuss it in more detail?

Here, the use case is, when you need to make the child communicate with its parent.

I have a section about it in [My tips for working with Elmish](https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd) 

*Sorry Medium doesn't seem to have anchor support so you have to search for `Make the child communicate with the parent` title by yourself...*

> As a default approach though, I would likely create a third function to return the third item of the pair.

I am not sure to understand

- `update` is the first function? 
- `effect` is the second function?
- what goes here?

> In your code that follows this part I quoted, I don't know how `Update.compose` is implemented. Could you share the implementation with us?

Actually `Update.compose` signature is probably wrong, but basically, it would do the glue code you don't like. Sorry, I don't have the energy to make a prototype for it.

I know that a library for it exist somewhere in the Fable ecosystem but I can't remember the name of it.

------------------------------------------

@Zaid-Ajaj commented before me and his solution is indeed legit. 

Because, you can create your own `update'` function which can have the signature you proposed.

**Comment by rommsen** [comment]
Btw.: most of our update functions do **not** return `Model * Cmd<Msg>`.  We try to build our applications in a way that only the topmost components can issue commands.

As @MangelMaxime said: update is just a function, so you can return whatever you want. Sometimes we are returning only `Model` and sometimes the components are returning an intention of what they are trying the parent component to achieve: `Model * Intention`.

**Comment by bender2k14** [comment]
> You know you could just break the update function into two smaller functions, right?

Of course.  That is literally what I am trying to have a discussion about: the advantages and disadvantages between having one function (`update`) that returns a pair (`'model * Cmd<'msg>`) vs a pair of functions (`update` and `effect`) that each return one thing (`'model` and `Cmd<'msg>` respectively).

Did I give the impression that I didn't know that?

**Comment by bender2k14** [comment]
> A match is not always straightforward, for example code taken from one of my application:

I am having a hard time understanding what your code is doing.  I think the main difficulty that I am having is not being able to see the full implementation of your `update` function.  It appears that you are matching on a pair of things, but I am not certain about that because the first few lines are missing.

Could you include the the full implementation of your `update` function?

It would also save me a lot of time if your example compiled but that is not necessary.

> How would we initialize the components?...Would we have `init` and `initEffect` functions?

There are certainly many things we could consider.  In this issue, I am very specifically and narrowly trying to only have a conversation about the advantages and disadvantages between having one function (`update`) that returns a pair (`'model * Cmd<'msg>`) vs a pair of functions (`update` and `effect`) that each return one thing (`'model` and `Cmd<'msg>` respectively).  I would prefer if we could focus on this and avoid potentially using logical fallacies such as slippery slope or straw man.

> Here, the use case is, when you need to make the child communicate with its parent.
> 
> I have a section about it in My tips for working with Elmish

Is your example missing a model type in the submodule `Login`?  Assuming it is, why not just have the model data of type `Session option` on that `Login.Model` type?

> Actually Update.compose signature is probably wrong, but basically, it would do the glue code you don't like. Sorry, I don't have the energy to make a prototype for it.
> 
> I know that a library for it exist somewhere in the Fable ecosystem but I can't remember the name of it.

I would definitely like to know if it is possible to implement your `Update.compose` function.  I thought about it but don't see how it is possible.  It may very well be possible, but I just don't know enough F# yet.  Please do share with us the implementation if you figure it out.

> @Zaid-Ajaj commented before me and his solution is indeed legit.
> 
> Because, you can create your own `update'` function which can have the signature you proposed.

I don't know what you mean by "legit".  I know I can create my own `update` and `effect` functions.  That is not why I created this issue.  I created this issue to discuss the advantages and disadvantages between having one function (`update`) that returns a pair (`'model * Cmd<'msg>`) vs a pair of functions (`update` and `effect`) that each return one thing (`'model` and `Cmd<'msg>` respectively).

**Comment by bender2k14** [comment]
> ..most of our update functions do **not** return `Model * Cmd<Msg>`.

And what about the cases in which you do choose that return type?  Those are the edges cases that I am interested in.

> ...update is just a function, so you can return whatever you want.

I know I can create my own `update` and `effect` functions.  That is not why I created this issue.  I did not create this issue to tell everyone what I want to do.  I created this issue to discuss the advantages and disadvantages between having one function (`update`) that returns a pair (`'model * Cmd<'msg>`) vs a pair of functions (`update` and `effect`) that each return one thing (`'model` and `Cmd<'msg>` respectively).

> ...sometimes the components are returning an intention of what they are trying the parent component to achieve: `Model * Intention`.

Yes.  I hadn't read about or considered this "intention pattern" before.  I will definitely think about it.  @MangelMaxime pointed out such an example from his blog post.  I think more examples would be helpful.

Do you have an example where you have used this "intention pattern" that you are willing to share with us?

**Comment by Nhowka** [comment]
I'm having a harder time thinking how it would be used outside an intention pattern. Most of the time the ` Cmd` is tightly coupled with the model change. You can for example do the following:

-  Start some loading screen and send a `Cmd` with an `Async` computation that will return the results.
- Load a new record from a list and use a `Cmd` to change the URL to reflect the id of said record.
- Show an error message and have a `Cmd` to clear the message after 10 seconds.

For me the `Cmd` only shines when it's coming from a specific `Msg`. I can't see how can I decide for an action having the old model and the new model, but I can decide for the next course of action on the current action alone.

So that's why we see lots of value on having the `update` giving us a `'model * Cmd<'msg>`. We have all the information about the flow, where we are and where we want to go on the moment we get that new message. It's hard to compose on the first time, but it becomes trivial on the second as it will mostly follow the same recipe everytime.

**Comment by halcwb** [comment]
If you want you're update to do less:

```
let update model = function
    | NavBarMsg _ -> model
    | _ -> model

let simpleUpdate update model msg = 
    update model msg, [] 


#if DEBUG
open Elmish.Debug
open Elmish.HMR
#endif

Program.mkProgram init (fun msg model -> simpleUpdate update model msg) view

```

And if you do need commands than I would do it as @Nhowka  suggests.

**Comment by MangelMaxime** [comment]
> I am having a hard time understanding what your code is doing. I think the main difficulty that I am having is not being able to see the full implementation of your update function. It appears that you are matching on a pair of things, but I am not certain about that because the first few lines are missing.

Yes, it's matching on several things, my purpose here was just to say that the match used in the `update` isn't always straightforward and so duplicating it increases the risk of bugs, incorrectness in the application.

> There are certainly many things we could consider. In this issue, I am very specifically and narrowly trying to only have a conversation about the advantages and disadvantages between having one function (update) that returns a pair ('model * Cmd<'msg>) vs a pair of functions (update and effect) that each return one thing ('model and Cmd<'msg> respectively). I would prefer if we could focus on this and avoid potentially using logical fallacies such as slippery slope or straw man.

My answers are in response to your question I am just pointing out the problems I see.

But, to answer your question, then no update it is not doing too much. It's doing just the right job :)

**Comment by et1975** [comment]
no, it's not.

**Comment by Zaid-Ajaj** [comment]
@et1975 Did you just close the issue with "No" as an answer without any further explanation as to why that is case 😂 if you think the question is answered by a participant in the thread, at least point out that that is your answer as well, since you are *the* maintainer of this repo or wait for the OP to close it himself if the question is answered, maybe there is a follow up discussion with better ideas. Closing the issue like this doesn't help anyone and is very unwelcoming to contributors
