### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by odytrice** [elmish/elmish#190]
### Description

The documentation for Elmish is severely lacking. I wish to add some documentation on two new areas

1. Making Http Requests
2. Handling different Change Events like OnSubmit, OnChange e.t.c.

**Comment by bender2k14** [comment]
Elmish doesn't depend on any front end, but it seems to me like you have a particular front end in mind.

Are you currently using Elmish in some project?

**Comment by et1975** [comment]
I'd welcome more documentation, but the areas you have in mind are intentially outside of the elmish core domain. 
Consider that elmish itself is platform-independent and runs on JS and .NET runtimes. And that's just two dimentions, but off the top of my head there are at least 2 different JS runtimes (node and the browser), different Http primitives (and a couple of different libraries on top of them) and that's just in Fable ecosystem! I could also name at least 3 view engines, but just in React ecosystem there could be vastly different ways to model the UI and consequently the set of elements,properties and events.

Personally I'm in favour of samples and templates when it comes to putting things together.

**Comment by MangelMaxime** [comment]
Hello, 

like Eugene said there several ways to do the thing when working with Elmish application because "Elmish core" is only one part of it.

Someone asked the same question on f# slack and here was my answer:

You can also find tutorials on the internet:
- [My tips for working with Elmish](https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd) (<-- this one is from me and perhaps a bit too advance if you are just starting)
And more to found on the internet
- [Fable and Fable-Elmish Step-by-Step: Creating a Calculator](https://medium.com/@zaid.naom/fable-and-fable-elmish-step-by-step-creating-a-calculator-fa2abe9594be)

There are also templates and examples made by the community: 

- [Fulma-demo](https://mangelmaxime.github.io/fulma-demo) a Q&A website, code should be simple to understand
- [Tabula rasa](https://github.com/Zaid-Ajaj/tabula-rasa) a sort of blogging platform which is more complex because it's doing Server and Client-side, all wired with "magic" libraries which can be good if you use F# on both sides.

There are also several Elmish examples available on the [Fable REPL](https://fable.io/repl) can be found under `Samples > Elmish`. 

- [Really simple app to demonstrate event handling](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNQBQBUD1AsiqfgIZRycFEoAxp0ooQpOJhAB3dgHM4GGXEog4ENPCSpM1AJogIcYRIBm7MHFAAneO1NrOAI0OVEOjL2uCMKSjEFKCFteUks0TkJYNF43DEpKAjQALgB6VJhkdGw5PwwIJywxVOoGAEpaEAIYCQAxZ1gsAGEQWywAKTQyf2sq6iqauHqnRoAlGE5A-uq6hpgsccnKLAAFXqTpwe1szYltzAWJqep0uBYAeQARBAAZWkoAT2qz8Ey4AF5qOG+4AG84ABq3Ag8GSkko1nkcAAvvcnvAWGgFJ8fnAAD5wJoYTikOQwIFQEFwECmcGQ3G0WBudh+OB0MofP6A4Hwd5wABE7JhABpMcAwFhSOIYLRTgBVFaXACCABUEJSYG4IAQwCJ4HRgEjkoi5AyNa8oNqDQyUT9gCIfFYkXBZJQMF8fhisTi8QSiaQYNI3fAALQAPgdqO+-29jI9XpZPL5AqFHtFqUBxAQAHU6bYwjBbJZbZ5FoEKtQqXAAG4oT1WA1wMDoAgWzym77V4twADamKgnDQMXZ5vYPsE4konHYma5AF1A0G2+wKG4200O12OTOqOzJ0GNz9Q6AwJksN715uN+dSM7cerTBAJDBm-64DesEPrHjKAB+YuRtF+slQr+Y7HnqGf7VmgtaUD4DITke3ygTirZwFB0HfG2aAQhyAASmRQCAvJrkhqKodYFa7lA+4soeR6ERyACE44IfGcBSvw1BrCAcjWJEWDAAA1qx7GRHANJKiqaolmW0jUH+fEccAWA5i0pBoCAsAyhxggilJvT8bJOZ5pQOAPKQPi9EKGgcpkHg+nwBBrppbEyVg1hXtQQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)
- [How to handle JSON and HTTP requests via Fetch](https://fable.io/repl/#?code=LYewJgrgNgpgBAFQBYgC5IHQCUCGA7MEYAVQGcYAnAKCoAoAqeqgZWByijhwAduoBLAMY5U-EHjikUAd354A5nBlxUIOBHIAuKgFpEKdBgBSpcXFpJUqbqU0B6O2wUwobAB79gMDPP7oIAEYYYnbIaEh2AFameHYAbgDMGJbAUACUunAAChRE-ORcBHAAYjCogkhwAIJZAJKkVPQZVCDcMBLMAJ6kqDDALW0SxTgBsBgAwiAUMAPtJSNjWDA4gqizQwveSyuoGDmtDa1zAKKu+UjrcKfA59jLq5dhhibiNA5wALIA8gAixwAyVFQnTacAA4u0wJQ4ABeKhwBFwAA+n3YM0RyJKfTRNAxPREQjgXmAAWhPxggnA0LhGIx5MpUIwPQocnk8NpCKRAD44PSqRh8GBkHNaOyORiAGYQPCrMR4MXizlwABEbFgyrgOh5fMZpAggkEMBgYFRsAVipRyol2PVmu1FP5eoNRpNpTV6MViJRcji7H4Jq1KoABhqANRwH1+k3h5VBiOkPAAclQXDgvoEJvTEHgEqm4MhlGV5s9JYx3N5DsZEpw-CgxYRzWBoLI1IVAG98wRoZpO1DqBzitAoAA5HBeOA95ms4vHNi1ieSVAshTF8YuKBZFB4eCTpfTjlfCUSoQwTfiHeL5dsjlVeQXuRrDkAIX4FHQYBwnQXPxEMAQng9DEsiEVAIGmBcpwUOAAF9cURfFREEIk+lJCgKwZVtFXeAB1JA5g0Vl9HCYwYgAGjgToQAgLhwLwNA4FzChDRNVQ4EIVMAEYVDUDj6zgd42F4QjSVQaQjQkdB4CMZgvmHBipjYFNBQoqi0KbGAGiwuwSjzGA3DHPgYHIuQVDwuBtzcFMoQwtCxLgWQOC4Z1SFINijW4CM8EYxS5T495lJ6KZ4D8LgU0klVcjQDUQAlOBVJUEFANpHVvBAAJIgpFNaClCQ7xTLU+Ixd5agkNKMtWNybPIuzhAkPSKQgXpCi-YoAGJCsRd5mDURi4D0gzYGq+BavUApemAbgphwCgv19FlNk00tYBTY8KB6PAx3gGE4Dyu4AEcIFfY0MCqFMAG0VQ2rxlQAbhVVaeg1ABddDHT3FdSzgZavpwdbNthHayn2w7pjAE7zsuzbbpVKBftQZ7Xt1d62Q6hEOwhLs0O23algOo6weKfgXBNZU70xjUMb7DAUv7T6SiHUdx22h7UCu+AYxVOBw1hv6vFRxFZxrThsaB3GQeOwniZVbFaw1FKmWR-mETXDgz23AGcZgPHQYwSWoBJw0ODlytvEg686cPY9DTVrbAd2MX8d1on9ZVbgtxgY2MIVq8leqO8NdFrXxbB064Au5VCACaHlRwO8Eflh9fZfN8kA-L8RftoPHdD8PI+jj9enjk2MALsoAN94DVjA23Ne146c9dkDq+j2GKDjuAXvls2YL4xtEs+KlhYVBxtP+EAcDAQiEKSke4FqWKNGhfI4GHc9yMkiQ-ETVzwrkPx+HYL7x8nj6vTgMeJ8ImK4BbNDWlEV4iveC+oRNaeFRRF-jTi2Lb+H4rYo8xTNMA6GlgEaWgKgVyJl8B9QoLkWmSpjjwKCmAGg6lPikEUDSM+pRyhIFwAQIgf8yxYnwUsUgk08AFGvhQyBAAeW+5EzZcg-mQioyCEE-z6m4eUVBZ6hxZkNJQOA4jwDoqNaErFJ6UNhp0Kg3095ZTSADF+hFV7bnIuMYAYMYofCwewghgpiHkGoPw7SxAsg-CqAgY4NBvrcBZL6JqeVCGEBIKY8wKjtqOLyAUNs-84DYXgBPE0OA3JyO4QkAADNE4ArlTCmXgAERqqgJD4E8ASMwy9QDgTiPkfgowkqEAAITZFyDccgTJYAwA8jE6JCplplOmJQ8QBRtp4IqBga0+CVSWGsLYBwFBjHAEXhQDAXg7A8H4HYDUZ0nqNLKM0jSVDyAID0imbaLTVneF6JZWgGQMTfRaZAmmAN5bHilsqE5UAoEaloAnLsbg4DRJvqY6mJsKCHMRNMUCFAJAXIqcwZGcAbmoDOdstpf4NlUFgt9CA3BS7mHifITQ+j5AqNoKAKEUA0WD28QqRSFQiQGNkOgNhnSjFEI8dCAqipvrbmkB8QesJ+ZEsqNilw9k-AXE+gA+y8AkCiJCXAQQYFph4BTGM-m7w7IAGt3IRhTNIJAtZ4DSBrKIKC4VGWSMQZ6T+x9v5jLtL7BEaioK0G6uOMZ3ySwogAPp2nPsfdR544IckZcynFWidEYEPPsSp3gYA8uhK4kZt8vGGIoTswxnCpgev4tpYJO16LhMhdQkJRRrLgCnvqZixoKVlAqDGqF5gvhyr1Soul4ov4mjGb6sGdFtyJpwvAeQabQUrLLcpHNJ9FDVjVWg0hlLS2ZvMPGtCKLq2sMVNJDAlJqEgDGJQLhKK+KTuNI2jAzaZiBKqHVFBd8DTVzANVPCEgekVEIjqmA0g9VFvwZOuBXCa0cnnYu0wK6j0vqmBgD4GlSCxyShiTdZ64DaKbe68xcAABqtRjjYXMBKvs38yWVG2KsZoii8ACHVo4-gzj4AocoCVXMEZF3jB5q5LMW1FkpiEOIKjv1XLbStOEsMFGmPUYVJPOIYcO58QupQ2BF1mMuRVIxvAz1+YXX4AJ8T0DKPUcE3TREF0XoLJLMyTmRZtNLjTOwbMgmFFlE8nh+ABGiNpiJkywDwHRXLrzCi1lGI+MKZU7QVU9n-accpFAKYKitPiguu5sTKnvMuWAzoAI4BOgyc+sJgzLnNP2LM1Z38Nm70WuwQqfJd6ANRd8-kHQchcwamVNhTVN6zKmLEWhDNVSMAYCLKZlMGWmr5ekGB1ziIuuFaA8V0gOgPzOAoBVg9v7j1itBuRQyv1hp4UEJW8Kn7l05mc0FTy3ksl4Ba2l9rTjMtdcjbQE1PZb4EqOWZgIr53yfl6xyMZGBk73c6BgBAIBmAoDfD+XowKrwHMTWFiDEXhAUBNCV0RIhpoJZC2xQjHmWMqnB2AUrbB27BZLBdY88hq5I4k8qTJ-sSscQAEwAA43Dk4p3DtTcngCKHC8jonw3cjSlfnptTnpmBMT1XsJu4FNOqc9CDxTKPppo8Xb0SVdPPShcR8zwn0v2gpiFcNvZqAdCGklZQY0cvEsI-40r1yyp1c6E1zoMS-B5CWB0OQG4sWXYldIPwAAXjAHQABWA33OktoWe4ODgjN4BY+52LiLJW-B+kEL7+nl44C3ZTmnDuIvPoR5Zyr2Xae6YXRIxQMjah2M6DdueDUz2VYbndman5BYC9eSL9WEv7ty-vMtieG2NeET58L-dHAOh2hiIC20VvlAMCC3nMLhZbW4AdfgF1jGlBfxPlSdk0gOWEcid6TghE30UlWG48jnftJ+CxXyBvje-MNQlYC5fBQXOOQuHIFfh-tJyy0FDCo5U++0nxhLyyNgGaFUYHRXUHFnc3S3HXXoUGOPATDPCTH-Q-FyGvL4PAKjIQStbKaUOAJ1N9bnBEGRbgEQYlUdCNUxGvILWTBPZURfYZJqcJXVMZBGafBxI7JqKA6Ea9F2Y-eA03fzCAYAahP-UAW7W0MPDEBXY3MA5XZdAQzeYbBIBGDTDqXglHWQwQpQ0VVVF2cQ2kVQ5UfgwQv-RQ1PDTEzb6LrIkFlQg4gyoY-b6Wgc-V1BQciLPVAK7cUdlKwnFblclC0F1O-RQDReAPAxUJcbMciLrHLPiQ1QI8wa1eAW1U1T6cIoyLLaQSNaVfwutPVZI0sasKAcgSI2zTI8g-wnrUI8UAooo9IsDRNcgWUMwE3PpSgNQErKUDgPCG3SwWAyQgnU3PCXIGLOLWAiQo3fotQyVGsbccbHPQ3DgtCWgBfdoJfXoFfA-eQjfGw-BO1bnBYxzXXSVVPVLGDKoXgKgfYeQYZYACZOVS464zyEKBFJFLrKgcse4scDAdDTDVALoGUJAXIOiDQaWM4KQHQHgbgIsd43IK4z4igaUIAA&html=DwCwLgtgNgfAUAAlAUwIYBN4O0iyyoLhgAOAtMgI4CuAlgG4C8A5AMID2AdmMt2QCoBPEsmYIAxlx7cWPAB5gA9OGgBuCSFQAnAM75G1MADMyADmZYcwHeK20SYBDq3jGAIgD6HgBIB5AMr8XopQtABGOopaaOJgAHQkWuzo1LG0XHEQtJxxAFY6bjDAijZ2DpbY1rb2js6unj4BQR4h4ZHRqLFk6OwQCUkpaRlZOfmFxaU1FUihnADWCNFQ7jpgglDIOiDI+G5E0UbuXn6BwaERiuI6kWHUUBComdlxVwUIitPAswtLK2sbWx2YD2IAOR0apxa50ir0UqCgUCeOVeew+cGK2wwWGAYWSggkUFQ13cqBI5Ek3FQ2WQWkKiCs6AYCFo6HcyHutC2ZFJJD24kJxLc7KyXJ540UjPo8GKuPQgmxykgsCAA&css=HQYwhgTgJsCWDOBaMA3MAXSACLBvAUDjgLZgAeiA7rFOgBYBcWAzAKwAMADmQNyFGkIAc1gA7JmACu6APZ8AvoVCQYCZGkwQsy6IlikhAUzz8cUBJwA2YAJ5MAZpcO9TWAFaT46WPZuIQMqLohkFMICHBEHxEWGCWsEKiesHE8GERhlGunGBQ5qJCTABMrNxY7OUKQA)

@et1975 I suppose we can have a page somewhere on the website which references a list of examples, resources that can be useful for people starting Elmish? It would be something similar to what I just did for example.

Thanks to that, people are a bit more guided and it's easier for them to find the information. What do you think?

**Comment by MangelMaxime** [comment]
> Personally I'm in favour of samples and templates when it comes to putting things together.

I have the same opinion, example and templates allow the user to quickly have an application to play with, experiments, etc. :)

**Comment by Zaid-Ajaj** [comment]
Me and @rommsen are making streams on Elmish explaining concepts from scratch:
 - [Introduction to the Elm Architecture with Elmish in F# and Fable](https://www.youtube.com/watch?v=3Qk4bWs7vrs)
 - [Todo List application with React, Elmish, F# and Fable](https://www.youtube.com/watch?v=zAfW_-m1u4k)
 - [HTTP with React, Elmish, F# and Fable](https://www.youtube.com/watch?v=_2U4pDj6tng)
 - More to come...

**Comment by odytrice** [comment]
Okay I see. I've built an app with Elmish a while ago and wanted to start a new project but I had forgotten about how to do a lot of things so I tried checking the docs and couldn't find much.

So what can I do to help to improve the docs? What topics are relevant to Elmish core (and/or other parts of the Fable Ecosystem) that I should start working on?

**Comment by et1975** [comment]
@odytrice The docs generation tooling is *old* and could use a refresh.
In terms of content - maybe look through the issues in each repo and see if there are questions/concerns and answers that worth putting directly in the docs in a coherent and distilled form?
I'm going to close this, but we can continue discussions as needed.
