### ISSUE TITLE
Forgot to handle exception in Program.withSubscription?

### ISSUE THREAD

**Issue by retendo** [elmish/elmish#191]
I'm currently porting Elmish to Swift. In Swift the type system forces you to be explicit about functions that can throw exceptions. That's why I came across an inconsistency in program.fs.

In 'withSubscription' there is no exception handling when calling 'program.subscribe model':

https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L55-L57

In contrast, in 'runWith' exceptions are handled:

https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L159-L163

Don't know if this is a real issue, but I thought I'd let you know.

**Comment by et1975** [comment]
Thanks for bringing this up, different languages certainly can point out interesting problems.
I don't think it's a problem in this case though because if you think where the `model` comes from in your 1st quote you'll realize that the exception handler in your 2nd quote is in the stack of that call.

**Comment by retendo** [comment]
True
